Adding Pipfile and Pipfile.lock for specifying the requirements/packages
aicoe-aiops/ocp-alert-prediction-public pull request #2
Opened 2020-08-13 03:55 UTC by suppathak

Along with my blog post, I also want to include  Pipfile and Pipfile.lock in order to give the information about the required packages for the analysis.

2020-08-13 16:49 UTC, chauhankaranraj requested changes

2020-08-13 16:49 UTC, chauhankaranraj commented on Pipfile
> +sklearn = "*"
```suggestion
scikit-learn = "*"
```
According to the pypi docs - https://pypi.org/project/sklearn/

2020-08-17 11:18 UTC, tumido approved these changes
LGTM :+1:

2020-08-17 14:02 UTC, chauhankaranraj commented
Thanks @suppathak, LGTM! Could you please squash commits?

2020-08-17 14:27 UTC, suppathak commented
> Thanks @suppathak, LGTM! Could you please squash commits?

Done! Thanks :)

2020-08-17 14:38 UTC, chauhankaranraj approved these changes

2020-08-17 14:39 UTC, merged